# -*- coding: utf-8 -*-
"""
publish-plan.py — Convert markdown plan to beautiful HTML with Tailwind + UTF-8.

Used by Fox Spirit after aggregating team_tasks results from 3 sub-agents.
Output HTML saves to D:/GoClaw-plans/ and prints a public URL.

Usage:
    python publish-plan.py --title "Plan name" --input path/to/plan.md
    python publish-plan.py --title "Plan" --input plan.md --slug custom-slug
"""
import argparse
import html as html_mod
import re
import sys
from datetime import datetime
from pathlib import Path

PLANS_DIR = Path(r"D:/GoClaw-plans")
SERVER_PORT = 8765
SERVER_BASE_URL = f"http://localhost:{SERVER_PORT}"

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="vi">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<script src="https://cdn.tailwindcss.com"></script>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif; }}
  .prose h1 {{ font-size: 1.875rem; font-weight: 700; color: #1e293b; margin: 1.5rem 0 1rem; }}
  .prose h2 {{ font-size: 1.5rem; font-weight: 600; color: #334155; margin: 1.25rem 0 0.75rem; border-bottom: 1px solid #e2e8f0; padding-bottom: 0.5rem; }}
  .prose h3 {{ font-size: 1.25rem; font-weight: 600; color: #475569; margin: 1rem 0 0.5rem; }}
  .prose h4 {{ font-size: 1.1rem; font-weight: 600; color: #475569; margin: 0.75rem 0 0.5rem; }}
  .prose p {{ color: #334155; line-height: 1.75; margin-bottom: 0.75rem; }}
  .prose ul {{ list-style: disc; margin-left: 1.5rem; margin-bottom: 0.75rem; }}
  .prose ol {{ list-style: decimal; margin-left: 1.5rem; margin-bottom: 0.75rem; }}
  .prose li {{ color: #334155; margin-bottom: 0.25rem; line-height: 1.6; }}
  .prose code {{ background: #f1f5f9; color: #db2777; padding: 0.125rem 0.375rem; border-radius: 0.25rem; font-size: 0.875rem; font-family: "SF Mono", Menlo, monospace; }}
  .prose pre {{ background: #0f172a; color: #e2e8f0; border-radius: 0.5rem; padding: 1rem; overflow-x: auto; margin: 1rem 0; }}
  .prose pre code {{ background: transparent; color: #e2e8f0; padding: 0; }}
  .prose blockquote {{ border-left: 4px solid #60a5fa; background: #eff6ff; padding: 0.5rem 1rem; font-style: italic; margin: 1rem 0; }}
  .prose table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
  .prose th {{ background: #f1f5f9; border: 1px solid #cbd5e1; padding: 0.5rem 0.75rem; text-align: left; font-weight: 600; }}
  .prose td {{ border: 1px solid #e2e8f0; padding: 0.5rem 0.75rem; }}
  .prose hr {{ border: 0; border-top: 1px solid #e2e8f0; margin: 1.5rem 0; }}
  .prose a {{ color: #2563eb; text-decoration: none; }}
  .prose a:hover {{ text-decoration: underline; }}
  .prose input[type="checkbox"] {{ margin-right: 0.5rem; }}
  @media print {{
    header, footer {{ display: none; }}
    main {{ box-shadow: none; border: 0; }}
  }}
</style>
</head>
<body class="bg-gradient-to-br from-slate-50 to-blue-50 min-h-screen">
<div class="max-w-4xl mx-auto px-4 py-8">
  <header class="mb-6 bg-white rounded-xl shadow-sm border border-slate-200 p-6">
    <div class="flex items-start justify-between mb-2 gap-3">
      <h1 class="text-2xl sm:text-3xl font-bold text-slate-900">{title}</h1>
      <span class="text-xs font-mono text-slate-400 whitespace-nowrap pt-1">{generated_at}</span>
    </div>
    <div class="flex items-center gap-2 text-sm text-slate-500">
      <span>🦊 Fox Spirit</span>
      <span class="text-slate-300">•</span>
      <span>nelson-ops-team</span>
    </div>
  </header>

  <main class="bg-white rounded-xl shadow-sm border border-slate-200 p-6 sm:p-8 prose">
{body}
  </main>

  <footer class="mt-6 text-center text-xs text-slate-400">
    Generated by publish-plan.py • Nelson Freight Intelligence
  </footer>
</div>
</body>
</html>
"""


def slugify(text: str) -> str:
    """Generate URL-safe slug from arbitrary text (Vietnamese-aware via ASCII strip)."""
    text = text.lower().strip()
    # Strip Vietnamese diacritics → ASCII
    replacements = {
        "à": "a", "á": "a", "ả": "a", "ã": "a", "ạ": "a",
        "ă": "a", "ằ": "a", "ắ": "a", "ẳ": "a", "ẵ": "a", "ặ": "a",
        "â": "a", "ầ": "a", "ấ": "a", "ẩ": "a", "ẫ": "a", "ậ": "a",
        "đ": "d",
        "è": "e", "é": "e", "ẻ": "e", "ẽ": "e", "ẹ": "e",
        "ê": "e", "ề": "e", "ế": "e", "ể": "e", "ễ": "e", "ệ": "e",
        "ì": "i", "í": "i", "ỉ": "i", "ĩ": "i", "ị": "i",
        "ò": "o", "ó": "o", "ỏ": "o", "õ": "o", "ọ": "o",
        "ô": "o", "ồ": "o", "ố": "o", "ổ": "o", "ỗ": "o", "ộ": "o",
        "ơ": "o", "ờ": "o", "ớ": "o", "ở": "o", "ỡ": "o", "ợ": "o",
        "ù": "u", "ú": "u", "ủ": "u", "ũ": "u", "ụ": "u",
        "ư": "u", "ừ": "u", "ứ": "u", "ử": "u", "ữ": "u", "ự": "u",
        "ỳ": "y", "ý": "y", "ỷ": "y", "ỹ": "y", "ỵ": "y",
    }
    for vi, en in replacements.items():
        text = text.replace(vi, en)
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[-\s]+", "-", text).strip("-")
    return text[:60] or "plan"


def markdown_to_html(md: str) -> str:
    """Convert markdown to HTML using python-markdown (installed) with sensible extensions."""
    try:
        import markdown
        return markdown.markdown(
            md,
            extensions=[
                "fenced_code",
                "tables",
                "nl2br",
                "sane_lists",
                "toc",
            ],
            output_format="html5",
        )
    except ImportError:
        # Fallback: escape and wrap in <pre> so content still shows
        return f"<pre>{html_mod.escape(md)}</pre>"


def main() -> int:
    # Force UTF-8 stdout
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except AttributeError:
        pass

    parser = argparse.ArgumentParser(description="Publish plan as HTML")
    parser.add_argument("--title", required=True, help="Plan title")
    parser.add_argument("--input", required=True, help="Input markdown file path")
    parser.add_argument("--slug", default="", help="Custom slug (default: auto from title)")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"ERROR: Input file not found: {input_path}", file=sys.stderr)
        return 1

    md_content = input_path.read_text(encoding="utf-8")
    body_html = markdown_to_html(md_content)

    PLANS_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%y%m%d-%H%M%S")
    slug = args.slug or slugify(args.title)
    filename = f"{timestamp}-{slug}.html"
    out_path = PLANS_DIR / filename

    html = HTML_TEMPLATE.format(
        title=html_mod.escape(args.title),
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
        body=body_html,
    )
    out_path.write_text(html, encoding="utf-8")

    url = f"{SERVER_BASE_URL}/{filename}"
    print(f"PUBLISHED: {url}")
    print(f"FILE: {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
