"""
enrich_monthly_report.py — Fill KICK BACK + Net Profit cols in monthly report
==============================================================================
Takes a monthly_report .xlsx (generated by monthly_report.py) and back-fills
columns U/V/W/X with KB Client / KB Carrier / KB Tax / Net Profit computed
by cost_addons.compute_net_profit.

Skip logic
----------
- Rows where col B (CRM_ID / SHIPPER) is blank or contains "TOTAL"
- Rows where col T (Profit Share, col 20) or derived gross is 0

Column mapping (1-indexed, matches monthly_report.py schema):
  B  (2)  CRM_ID / Shipper name
  T  (20) Profit Share  <- gross_profit source
  U  (21) KICK BACK Client
  V  (22) KICK BACK Carrier
  W  (23) KICK BACK Tax
  X  (24) Net Profit

Since monthly report is a separate output file (not the v14 xlsm), normal
openpyxl save is fine — no ribbon preservation needed.

Usage
-----
  python ERP/intelligence/enrich_monthly_report.py monthly.xlsx
  python ERP/intelligence/enrich_monthly_report.py monthly.xlsx --rules custom.yaml
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import openpyxl
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side

# Add repo root to path for ERP package import
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from ERP.intelligence.cost_addons import compute_net_profit, load_rules  # noqa: E402

# Column indices (1-based, matching monthly_report.py schema)
COL_CRM = 2      # B — Shipper/CRM_ID
COL_CONT = 15    # O — HC (40HC volume; used to infer container type)
COL_PROFIT = 20  # T — Profit Share (gross profit)
COL_KB_CLIENT = 21   # U
COL_KB_CARRIER = 22  # V
COL_KB_TAX = 23      # W
COL_NET = 24         # X

_THIN = Side(style="thin", color="888888")
_BORDER = Border(
    left=_THIN, right=_THIN, top=_THIN, bottom=_THIN
)


def _money_style(cell, value: float, *, bold: bool = False) -> None:
    cell.value = value
    cell.number_format = '"$"#,##0.00'
    cell.alignment = Alignment(horizontal="center", vertical="center")
    cell.border = _BORDER
    color = None
    if bold:
        if value > 0:
            color = "00804A"
        elif value < 0:
            color = "C00000"
    cell.font = Font(
        size=10,
        name="Segoe UI",
        bold=bold,
        color=color or "000000",
    )


def _find_data_rows(ws) -> list[int]:
    """Return 1-based row numbers for data rows (skip header, TOTAL, blank)."""
    data_rows = []
    for row in ws.iter_rows(min_row=2):
        rn = row[0].row
        crm_cell = ws.cell(rn, COL_CRM)
        crm = str(crm_cell.value or "").strip().upper()
        if not crm or crm == "TOTAL":
            continue
        data_rows.append(rn)
    return data_rows


def enrich(xlsx_path: str, rules_path: str | None = None) -> dict:
    """
    Open xlsx, compute KB/net cols for every eligible row, save in-place.

    Returns summary stats.
    """
    rules = load_rules(rules_path)

    wb = openpyxl.load_workbook(xlsx_path)
    ws = wb.active

    enriched = 0
    skipped = 0
    total_net = 0.0

    data_rows = _find_data_rows(ws)

    for rn in data_rows:
        crm = str(ws.cell(rn, COL_CRM).value or "").strip()
        profit_raw = ws.cell(rn, COL_PROFIT).value

        try:
            gross = float(profit_raw or 0)
        except (TypeError, ValueError):
            gross = 0.0

        if gross == 0:
            skipped += 1
            continue

        # Build minimal job_row — monthly report has limited fields
        job_row = {
            "CRM_ID": crm,
            "Profit": gross,
            "Quantity": 1,
            "Container_Type": "40HC",  # default; monthly report aggregates
            "Selling_Rate": 0,
            "Buying_Rate": 0,
            "Status": "PAID",          # monthly report = already closed
            "SERVICE": "CY-CY",        # conservative; no trucking by default
            "Door_Address": "",
            "cargo_value": 0,
            "insurance_class": "",
        }

        result = compute_net_profit(job_row, rules)

        _money_style(ws.cell(rn, COL_KB_CLIENT), result["kb_client"])
        _money_style(ws.cell(rn, COL_KB_CARRIER), result["kb_carrier"])
        _money_style(ws.cell(rn, COL_KB_TAX), result["kb_tax"])
        _money_style(ws.cell(rn, COL_NET), result["net_profit"], bold=True)

        total_net += result["net_profit"]
        enriched += 1

    wb.save(xlsx_path)
    wb.close()

    return {
        "enriched": enriched,
        "skipped": skipped,
        "total_net": total_net,
        "path": xlsx_path,
    }


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Enrich monthly report with KB + net profit columns"
    )
    ap.add_argument("xlsx", help="Path to monthly report .xlsx file")
    ap.add_argument(
        "--rules",
        default=None,
        help="Path to commissions_rules.yaml (default: ERP/data/commissions_rules.yaml)",
    )
    args = ap.parse_args()

    path = Path(args.xlsx)
    if not path.exists():
        print(f"[ERROR] File not found: {path}", file=sys.stderr)
        return 1

    print(f"[+] Enriching: {path}")
    stats = enrich(str(path), args.rules)
    print(f"    -> enriched : {stats['enriched']} rows")
    print(f"    -> skipped  : {stats['skipped']} rows (zero profit or TOTAL)")
    print(f"    -> total net: ${stats['total_net']:,.2f}")
    print(f"[OK] Saved in-place: {stats['path']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
